apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus        # Unique ID for referencing in dashboards
    access: proxy          # Grafana proxies requests
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "5s"
